Vagrant.configure("2") do |config|
  config.vm.box = "debian/buster64"
  config.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine
    vb.gui = true
    # Customize the amount of memory on the VM
    vb.memory = "2048"
    # Give easy name (without timestamp) for the VM
    vb.name = "sardana-icalepcs2019"
    # Disable Guest Additions update
    config.vbguest.auto_update = false
    # Increase Video Memory
    vb.customize ["modifyvm", :id, "--vram", "10"]
    # Add IDE controller (for optical drive)
    vb.customize ["storagectl", :id,
                  "--name", "IDE",
                  "--add", "ide"]
    # Add optical drive
    vb.customize ["storageattach", :id,
                  "--storagectl", "IDE",
                  "--port", "0", "--device", "1",
                  "--type", "dvddrive",
                  "--medium", "emptydrive"]
  end
  config.vm.provision "shell", path: "provision.sh"
end
